name: "Deploy Site para VPS"
on:
  push:
    branches:
      - main
jobs:
  build_deploy:
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Baixar o c처digo
      - name: "Baixar o c처digo"
        uses: actions/checkout@v4

      # Passo 2:  build localmente
      - name: "Build Local"
        run: |
          npm install --legacy-peer-deps --no-progress -a
          npx ng build --configuration production

      # Passo 3: Copiar arquivos para a VPS
      - name: "Copiar arquivos para VPS"
        uses: appleboy/scp-action@v0.1.7
        with:
          host: "147.79.81.28"
          username: "userdeploy"
          key: ${{ secrets.SSH_PRIVATE_SITE }}
          source: "/dist/site_preparacao/browser/*"
          target: /var/www/site_preparacao

      # Passo 4: Ajustar permiss천es na VPS
      - name: "Ajustando permiss천es na VPS"
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: "147.79.81.28"
          username: "userdeploy"
          key: ${{ secrets.SSH_PRIVATE_SITE }}
          script: |
            sudo chown -R userdeploy:userdeploy /var/www/site_preparacao
            sudo systemctl restart nginx
